# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import re

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(448, 641)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(10, 20, 428, 131))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.l1.setFont(font)
        self.l1.setFrameShape(QtWidgets.QFrame.Box)
        self.l1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l1.setObjectName("l1")
        self.l1.setStyleSheet("background-color:white")
        self.b1 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b1))
        self.b1.setGeometry(QtCore.QRect(10, 170, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b2))
        self.b2.setGeometry(QtCore.QRect(120, 170, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b3))
        self.b3.setGeometry(QtCore.QRect(230, 170, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b3.setFont(font)
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b4))
        self.b4.setGeometry(QtCore.QRect(340, 170, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b4.setFont(font)
        self.b4.setObjectName("b4")
        self.b5 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b5))
        self.b5.setGeometry(QtCore.QRect(10, 260, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b5.setFont(font)
        self.b5.setObjectName("b5")
        self.b6 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b6))
        self.b6.setGeometry(QtCore.QRect(120, 260, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b6.setFont(font)
        self.b6.setObjectName("b6")
        self.b7 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b7))
        self.b7.setGeometry(QtCore.QRect(230, 260, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b7.setFont(font)
        self.b7.setObjectName("b7")
        self.b8 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b8))
        self.b8.setGeometry(QtCore.QRect(340, 260, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b8.setFont(font)
        self.b8.setObjectName("b8")
        self.b9 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b9))
        self.b9.setGeometry(QtCore.QRect(10, 350, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b9.setFont(font)
        self.b9.setObjectName("b9")
        self.b10 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b10))
        self.b10.setGeometry(QtCore.QRect(120, 350, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b10.setFont(font)
        self.b10.setObjectName("b10")
        self.b11 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b11))
        self.b11.setGeometry(QtCore.QRect(230, 350, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b11.setFont(font)
        self.b11.setObjectName("b11")
        self.b12 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b12))
        self.b12.setGeometry(QtCore.QRect(340, 350, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b12.setFont(font)
        self.b12.setObjectName("b12")
        self.b13 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b13))
        self.b13.setGeometry(QtCore.QRect(10, 440, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b13.setFont(font)
        self.b13.setObjectName("b13")
        self.b14 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b14))
        self.b14.setGeometry(QtCore.QRect(120, 440, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b14.setFont(font)
        self.b14.setObjectName("b14")
        self.b15 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b15))
        self.b15.setGeometry(QtCore.QRect(230, 440, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b15.setFont(font)
        self.b15.setObjectName("b15")
        self.b16 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b16))
        self.b16.setGeometry(QtCore.QRect(340, 440, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b16.setFont(font)
        self.b16.setObjectName("b16")
        self.b17 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b17))
        self.b17.setGeometry(QtCore.QRect(10, 530, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b17.setFont(font)
        self.b17.setObjectName("b17")
        self.b18 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press(self.b18))
        self.b18.setGeometry(QtCore.QRect(120, 530, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b18.setFont(font)
        self.b18.setObjectName("b18")
        self.b19 = QtWidgets.QPushButton(self.centralwidget, clicked = self.dot)
        self.b19.setGeometry(QtCore.QRect(230, 530, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b19.setFont(font)
        self.b19.setObjectName("b19")
        self.b20 = QtWidgets.QPushButton(self.centralwidget, clicked = self.equal)
        self.b20.setGeometry(QtCore.QRect(340, 530, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.b20.setFont(font)
        self.b20.setObjectName("b20")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 448, 26))
        self.menubar.setObjectName("menubar")
        self.menuCalculator = QtWidgets.QMenu(self.menubar)
        self.menuCalculator.setObjectName("menuCalculator")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuCalculator.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.l1.setText(_translate("MainWindow", "0"))
        self.b1.setText(_translate("MainWindow", "%"))
        self.b2.setText(_translate("MainWindow", "C"))
        self.b3.setText(_translate("MainWindow", "<"))
        self.b4.setText(_translate("MainWindow", "/"))
        self.b5.setText(_translate("MainWindow", "7"))
        self.b6.setText(_translate("MainWindow", "8"))
        self.b7.setText(_translate("MainWindow", "9"))
        self.b8.setText(_translate("MainWindow", "x"))
        self.b9.setText(_translate("MainWindow", "4"))
        self.b10.setText(_translate("MainWindow", "5"))
        self.b11.setText(_translate("MainWindow", "6"))
        self.b12.setText(_translate("MainWindow", "+"))
        self.b13.setText(_translate("MainWindow", "1"))
        self.b14.setText(_translate("MainWindow", "2"))
        self.b15.setText(_translate("MainWindow", "3"))
        self.b16.setText(_translate("MainWindow", "-"))
        self.b17.setText(_translate("MainWindow", "0"))
        self.b18.setText(_translate("MainWindow", "00"))
        self.b19.setText(_translate("MainWindow", "."))
        self.b20.setText(_translate("MainWindow", "="))
        self.menuCalculator.setTitle(_translate("MainWindow", "Calculator"))

    # def plus_minus(self):
    #     s = self.l1.text()
    #     if s[0] == "0" and len(s) == 1:
    #         self.l1.setText("-")
    #     elif s[0] == "-":
    #         self.l1.setText(s[1:])
    #     else:
    #         self.l1.setText("-"+s)

    def equal(self):
        s = self.l1.text()
        try:
            ans = str(eval(s))
            if len(ans)>18:
                self.l1.setText(ans[0:18])
                print(ans)
            else:
                self.l1.setText(ans)
        except Exception as e1:
            pass

    def press(self, b):
        if b.text() == "C":
            self.l1.setText("0")

        elif b.text() == "<":
            s = self.l1.text()
            s = s[0:len(self.l1.text())-1]
            if len(s)==0:
                self.l1.setText("0")    
            else:
                self.l1.setText(s)

        else:
            if self.l1.text() == "0":
                self.l1.setText(""+b.text())    
            else:
                if b.text() == "x":
                    self.l1.setText(self.l1.text()+"*")
                elif len(self.l1.text())<17:
                    self.l1.setText(self.l1.text()+b.text())

    def dot(self):
        s = self.l1.text()
        l = re.split("[- + * /]", s)

        if len(l)==1 and "." not in l[-1]:
            self.l1.setText(self.l1.text()+".")
        else:
            if "." in l[-1]:
                pass
            else:
                self.l1.setText(self.l1.text()+".")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
