# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TicTacToe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    c = 0
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 466)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b1 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda:  self.click(self.b1))
        self.b1.setGeometry(QtCore.QRect(0, 10, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.b1.setFont(font)
        self.b1.setText("")
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.click(self.b2))
        self.b2.setGeometry(QtCore.QRect(140, 10, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.b2.setFont(font)
        self.b2.setText("")
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.click(self.b3))
        self.b3.setGeometry(QtCore.QRect(280, 10, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.b3.setFont(font)
        self.b3.setText("")
        self.b3.setObjectName("b3")
        self.b5 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.click(self.b5))
        self.b5.setGeometry(QtCore.QRect(140, 140, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.b5.setFont(font)
        self.b5.setText("")
        self.b5.setObjectName("b5")
        self.b4 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.click(self.b4))
        self.b4.setGeometry(QtCore.QRect(0, 140, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.b4.setFont(font)
        self.b4.setText("")
        self.b4.setObjectName("b4")
        self.b6 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.click(self.b6))
        self.b6.setGeometry(QtCore.QRect(280, 140, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.b6.setFont(font)
        self.b6.setText("")
        self.b6.setObjectName("b6")
        self.b8 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.click(self.b8))
        self.b8.setGeometry(QtCore.QRect(140, 270, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.b8.setFont(font)
        self.b8.setText("")
        self.b8.setObjectName("b8")
        self.b7 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.click(self.b7))
        self.b7.setGeometry(QtCore.QRect(0, 270, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.b7.setFont(font)
        self.b7.setText("")
        self.b7.setObjectName("b7")
        self.b9 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.click(self.b9))
        self.b9.setGeometry(QtCore.QRect(280, 270, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.b9.setFont(font)
        self.b9.setText("")
        self.b9.setObjectName("b9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def click(self, b):
        if b.text()=="":
            if self.c%2==0:
                b.setText("o")
                if self.winner("o"):
                    ans = QtWidgets.QMessageBox.question(b,"Player 'o' Wins", "Want to play again?")
                    if ans == QtWidgets.QMessageBox.Yes:
                        self.reset()
                        return
                    else:
                        sys.exit()
                elif self.tie():
                    ans = QtWidgets.QMessageBox.question(b,"Match Ties", "Want to play again?")
                    if ans == QtWidgets.QMessageBox.Yes:
                        self.reset()
                    else:
                        sys.exit()
            else:
                b.setText("x")
                if self.winner("x"):
                    ans = QtWidgets.QMessageBox.question(b,"Player 'x' Wins", "Want to play again?")
                    if ans == QtWidgets.QMessageBox.Yes:
                        self.reset()
                        return
                    else:
                        sys.exit()
                elif self.tie():
                    ans = QtWidgets.QMessageBox.question(b,"Match Ties", "Want to play again?")
                    if ans == QtWidgets.QMessageBox.Yes:
                        self.reset()
                    else:
                        sys.exit()
            self.c+=1

    def winner(self, s1):
        return (self.b1.text()==s1 and self.b2.text()==s1 and self.b3.text()==s1 or
                self.b4.text()==s1 and self.b5.text()==s1 and self.b6.text()==s1 or
                self.b7.text()==s1 and self.b8.text()==s1 and self.b9.text()==s1 or
                self.b1.text()==s1 and self.b4.text()==s1 and self.b7.text()==s1 or
                self.b2.text()==s1 and self.b5.text()==s1 and self.b8.text()==s1 or
                self.b3.text()==s1 and self.b6.text()==s1 and self.b9.text()==s1 or
                self.b1.text()==s1 and self.b5.text()==s1 and self.b9.text()==s1 or
                self.b3.text()==s1 and self.b5.text()==s1 and self.b7.text()==s1)
    
    def tie(self):
        return (self.b1.text()!="" and self.b2.text()!="" and self.b3.text()!="" and
                self.b4.text()!="" and self.b5.text()!="" and self.b6.text()!="" and
                self.b7.text()!="" and self.b8.text()!="" and self.b9.text()!="")

    def reset(self):
        self.b1.setText("")
        self.b2.setText("")
        self.b3.setText("")
        self.b4.setText("")
        self.b5.setText("")
        self.b6.setText("")
        self.b7.setText("")
        self.b8.setText("")
        self.b9.setText("")
        self.c = 0

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
